server:
  port: 9009


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/community?serverTimezone=UTC&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
mybatis:
  configuration:
    map-underscore-to-camel-case: true

qiniu:
  ak: 8MXvyykVC3HjCJSWLSdzrdLCquCnNWXoThppE_zX
  sk: AD2o5FD6X-HxK47Gx9Ixm-KnX5wXbV9E7NrFoRaN
  bucket: kilsme-community
  domain: http://t29ukbztc.hn-bkt.clouddn.com

langchain4j:
  open-ai:
    chat-model:
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      api-key: ${API-KEY}
      model-name: qwen-plus
      log-requests: true
      log-responses: true
logging:
  level:
    dev.langchain4j: debug

